# Generated by Django 4.2.7 on 2023-12-03 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('1 ère', '1 ère'), ('2 ème', '2 ème'), ('3 ème', '3 ème')], max_length=10)),
                ('students', models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='classes_as_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
