# Generated by Django 4.2.7 on 2023-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dayofweek',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='hour',
            field=models.CharField(choices=[('morning', '9h00 - 12h15'), ('afternoon', '13h15 - 16h30')], default='morning', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2')], default='semester1', max_length=10),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
