# Generated by Django 4.2.7 on 2023-12-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_dayofweek_course_hour_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hour',
            field=models.CharField(choices=[('9h00 - 12h15', '9h00 - 12h15'), ('13h15 - 16h30', '13h15 - 16h30')], default='9h00 - 12h15', max_length=20),
        ),
    ]
